
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/houseUtilsApp?characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: doseong9114!!


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug